/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-13 08:28:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/D:/webSpring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stay/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/webSpring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stay/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/webSpring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stay/WEB-INF/lib/jstl-1.2.jar!/META-INF/x.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1574831910286L));
    _jspx_dependants.put("jar:file:/D:/webSpring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stay/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/webSpring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/stay/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<!--bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<!--font-awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- datepicker -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("@font-face { font-family: 'Eoe_Zno_L'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_eight@1.0/Eoe_Zno_L.woff') format('woff'); font-weight: normal; font-style: normal; }\r\n");
      out.write("@font-face { font-family: 'S-CoreDream-2ExtraLight'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-2ExtraLight.woff') format('woff'); font-weight: normal; font-style: normal; }\r\n");
      out.write("@font-face { font-family: 'KBIZHanmaumGothic'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/KBIZHanmaumGothic.woff') format('woff'); font-weight: normal; font-style: normal; }\r\n");
      out.write(".header {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-bottom: 1px solid #e5e5e5;\r\n");
      out.write("    z-index: 999;\r\n");
      out.write("    width : 100%;\r\n");
      out.write("}\r\n");
      out.write(".carousel {\r\n");
      out.write("\tmargin-top : 100px;\r\n");
      out.write("}\r\n");
      out.write("nav, figure, footer, header {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("figure {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header #logo {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    line-height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header #logo img {\r\n");
      out.write("    transition: all .2s ease-in-out;\r\n");
      out.write("    width: 300px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .navbar {\r\n");
      out.write("    border-left: 1px solid #e5e5e5;\r\n");
      out.write("    border-right: 1px solid #e5e5e5;\r\n");
      out.write("    border-top: 0;\r\n");
      out.write("    border-bottom: 0;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    border-radius: 0;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin-left: -15px;\r\n");
      out.write("    margin-right: 15px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    min-height: 50px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .top-navbar {\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("    border-bottom: 1px solid #e5e5e5;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write(".header .search-box {\r\n");
      out.write("    width: 40%;\r\n");
      out.write("}\r\n");
      out.write(".header .link-box, .header .search-box {\r\n");
      out.write("    float: left;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .link-box {\r\n");
      out.write("    width: 30%;\r\n");
      out.write("    border-left: 1px solid #e5e5e5;\r\n");
      out.write("}\r\n");
      out.write(".header .link-box ul {\r\n");
      out.write("    margin: 0 2% 0 3%;\r\n");
      out.write("    width: 93%;\r\n");
      out.write("    display: -webkit-flex;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -webkit-justify-content: space-around;\r\n");
      out.write("    -ms-flex-pack: distribute;\r\n");
      out.write("    justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .link-box li {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write(".header .link-box li a, .header .search-box a {\r\n");
      out.write("\tfont-family: 'Eoe_Zno_L';\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .main-navbar ul {\r\n");
      out.write("\tfont-family: 'Eoe_Zno_L';\r\n");
      out.write("    margin: 0 2% 0 3%;\r\n");
      out.write("    width: 93%;\r\n");
      out.write("    display: -webkit-flex;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -webkit-justify-content: space-around;\r\n");
      out.write("    -ms-flex-pack: distribute;\r\n");
      out.write("    justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .main-navbar li {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write(".header .main-navbar li a {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-caption p {\r\n");
      out.write("   font-family: 'S-CoreDream-2ExtraLight';\r\n");
      out.write("   font-size: 30px;\r\n");
      out.write("   font-style: italic;\r\n");
      out.write("   margin-bottom: 80px;\r\n");
      out.write("   margin-left: 50%;\r\n");
      out.write("   width:600px;\r\n");
      out.write("   position: relative;\r\n");
      out.write("   background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("   transform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("/************************************/\r\n");
      out.write(".booking-form {\r\n");
      out.write("   font-family: 'Eoe_Zno_L';\r\n");
      out.write("   color : white;\r\n");
      out.write("}\r\n");
      out.write(".input-grp {\r\n");
      out.write("   width : 150px;\r\n");
      out.write("   display : inline-block;\r\n");
      out.write("   margin: 30px 10px;\r\n");
      out.write("}\r\n");
      out.write(".form-control {\r\n");
      out.write("   font-size : 12px;\r\n");
      out.write("   background : transparent;\r\n");
      out.write("   border-radius : 0;\r\n");
      out.write("   color:#fff;\r\n");
      out.write("   box-shadow: none;\r\n");
      out.write("   margin : 0px 50px;\r\n");
      out.write("   height : 33px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".custom-select {\r\n");
      out.write("   background : black;\r\n");
      out.write("   color : #fff;\r\n");
      out.write("   font-size:12px;\r\n");
      out.write("   border : 1px solid #ced4da;\r\n");
      out.write("   box-shadow: none;\r\n");
      out.write("   border-radius : 0;\r\n");
      out.write("   background : transparent;\r\n");
      out.write("   margin : 0px 50px;\r\n");
      out.write("   height : 33px;\r\n");
      out.write("}\r\n");
      out.write("option {\r\n");
      out.write("   background : #343a40;\r\n");
      out.write("   font-size:12px;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"number\"]::-webkit-outer-spin-button,\r\n");
      out.write("input[type=\"number\"]::-webkit-inner-spin-button {\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner {\r\n");
      out.write("   /*float: left;*/\r\n");
      out.write("    margin: 10px 0;\r\n");
      out.write("    /*position: relative;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    background-color: rgba(0,0,0,.5);\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner img {\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("    display: block;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".centered {\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("\tfont-family: 'S-CoreDream-2ExtraLight';\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-shadow: 0 1px #000;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.2);\r\n");
      out.write("    width: 80px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    border: 2px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner:hover img {\r\n");
      out.write("\tz-index: -1;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("/************************************/\r\n");
      out.write(".container-fluid {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*##################################*/\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("\t.container {\r\n");
      out.write("\t\tmax-width: 1000px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.header #logo img {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    margin-left: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu-toggle {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\twidth: 40px;\r\n");
      out.write("\t\theight: 70px;\r\n");
      out.write("\t\tmargin: 5px;\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 30px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu-toggle:before {\r\n");
      out.write("\t\tcontent: '\\f0c9';\r\n");
      out.write("\t\tfont-family: fontAwesome;\r\n");
      out.write("\t\tline-height:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav {\r\n");
      out.write("\t\tdisplay:none!important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav.active {\r\n");
      out.write("\t\tdisplay: block!important;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\tmargin-left: 0!important;\r\n");
      out.write("    \tmargin-right: 0!important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav.active .top-navbar {\r\n");
      out.write("\t\tborder-top: 1px solid #e5e5e5;\r\n");
      out.write("\t\tmargin-right: 10px;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.form-control, .custom-select {\r\n");
      out.write("\t\tmargin:0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.input-grp {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tmargin: 10px 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (min-width: 768px) and (max-width: 1200px) {\r\n");
      out.write("\t.input-grp {\r\n");
      out.write("\t\tmargin: 20px 20px;\r\n");
      out.write("\t\twidth: 25%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("\t height:300px;\r\n");
      out.write("\t width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*##################################*/\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header id=\"header\" class=\"header\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <figure id=\"logo\" class=\"col-md-6\">\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("        \t<img src=\"img/logo.jpg\" id=\"logoimg\" alt=\"stay with me\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"menu-toggle\"></div>\r\n");
      out.write("      </figure>\r\n");
      out.write("      \r\n");
      out.write("      <nav class=\"navbar col-md-6\" id=\"top-nav-bar\">\r\n");
      out.write("        <div class=\"top-navbar row\">\r\n");
      out.write("          <div class=\"search-box\">\r\n");
      out.write("          \t<a href=\"#\">지역별 숙소찾기</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"link-box\">\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("              \t<li class=\"qna-btn-li\"><a href=\"#\">Q&A</a></li>\r\n");
      out.write("            \t<li class=\"cs-btn-li\"><a href=\"#\">고객센터</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"link-box\">\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("              \t<li class=\"login-btn-li\"><a href=\"#\">로그인</a></li>\r\n");
      out.write("            \t<li class=\"signup-btn-li\"><a href=\"#\">회원가입</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"main-nav-bar\" class=\"main-navbar row\">\r\n");
      out.write("          <ul class=\"list-unstyled\">\r\n");
      out.write("            <li class=\"wish-btn-li\"><a href=\"#\">위시리스트</a></li>\r\n");
      out.write("            <li class=\"confirm-btn-li\"><a href=\"#\">예약확인</a></li>\r\n");
      out.write("            <li class=\"host-btn-li\"><a href=\"#\">호스트</a></li>\r\n");
      out.write("            <li class=\"message-btn-li\"><a href=\"#\">쪽지</a></li>\r\n");
      out.write("            <li class=\"notice-btn-li\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- Carousel -->\r\n");
      out.write("<div class=\"container-fluid carousel\">\r\n");
      out.write("\t<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t<!-- Indicators(사진 순서 표시하는 작은 막대기들) -->\r\n");
      out.write("\t\t<ul class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active bg-light\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\" class=\"bg-light\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\" class=\"bg-light\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"3\" class=\"bg-light\"></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!-- 실제 내용(사진+설명) -->\r\n");
      out.write("\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t<img style=\"height:500px; width:100%; margin:0;\" src=\"img/1.jpg\" alt=\"seoul\" class=\"d-block mx-auto\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p>여행과 장소의 변화는<br/>\r\n");
      out.write("\t\t\t\t\t우리 마음에 활력을 선사한다<br/>\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size:15px;\">세네카</span></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t<img style=\"height:500px; width:100%; margin:0;\" src=\"img/2.jpg\" alt=\"LA\" class=\"d-block mx-auto\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p>바보는 방황하고,<br/>\r\n");
      out.write("\t\t\t\t\t현명한 사람은 여행한다.<br/>\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size:15px;\">토마스 풀러</span></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t<img style=\"height:500px; width:100%; margin:0;\" src=\"img/3.jpg\" alt=\"3\" class=\"d-block mx-auto\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p>낯선 땅이란 없다.<br/>\r\n");
      out.write("\t\t\t\t\t단지 여행자가 낯설 뿐이다.<br/>\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size:15px;\">로버트 루이스 스티븐슨</span></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t<img style=\"height:500px; width:100%; margin:0;\" src=\"img/4.jpg\" alt=\"4\" class=\"d-block mx-auto\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p>희망차게 여행하는 것이<br/>\r\n");
      out.write("\t\t\t\t\t목적지에 도착하는 것보다 좋다.<br/>\r\n");
      out.write("\t\t\t\t<span style=\"font-size:15px;\">로버트 루이스</span></p>\r\n");
      out.write("\t\t\t</div><!-- carousel-item(4개) --> \r\n");
      out.write("\t\t  </div><!-- carousel-item(2개) -->\r\n");
      out.write("       </div> <!-- carousel-inner(1개) -->\r\n");
      out.write("\t </div> <!-- carousel (1개) -->\r\n");
      out.write("</div> <!-- container -->\r\n");
      out.write("\r\n");
      out.write("<!-- Booking Form -->\r\n");
      out.write("<div class=\"container-fluid bg-dark\">\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<div class=\"booking-form container input-group\">\r\n");
      out.write("\t\t\t<div class=\"input-grp\">\r\n");
      out.write("\t\t\t\t<select class=\"custom-select\" name=\"Area\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"#\">&nbsp;&nbsp;지역&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">&nbsp;&nbsp;강원&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t   \t<option value=\"2\">&nbsp;&nbsp;경기&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t   \t<option value=\"3\">&nbsp;&nbsp;경남&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"4\">&nbsp;&nbsp;경북&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"5\">&nbsp;&nbsp;대구&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t   \t<option value=\"6\">&nbsp;&nbsp;부산&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t   \t<option value=\"7\">&nbsp;&nbsp;서울&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"8\">&nbsp;&nbsp;인천&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"8\">&nbsp;&nbsp;전남&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"8\">&nbsp;&nbsp;전북&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"8\">&nbsp;&nbsp;제주&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"8\">&nbsp;&nbsp;충남&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"8\">&nbsp;&nbsp;충북&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-grp\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"CheckIn\" class=\"form-control select-date\" value=\"Check In\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-grp\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"CheckOut\"class=\"form-control select-date\" value=\"Check Out\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"input-grp\">\r\n");
      out.write("\t            <input type=\"number\"  class=\"form-control\" placeholder=\"Adult\">\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"input-grp\">\r\n");
      out.write("\t            <input type=\"number\"  class=\"form-control\" placeholder=\"Child\">\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t\t<div class=\"input-grp\">\r\n");
      out.write("\t            <input type=\"submit\"  class=\"form-control\" value=\"제출\">\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 사진 카드 -->\r\n");
      out.write("<div class=\"container mt-3 mb-3\">\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">서울</div>\r\n");
      out.write("            <img alt=\"seoul\" src=\"img/seoul.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">제주</div>\r\n");
      out.write("            <img alt=\"jongno\" src=\"img/jeju.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">인천</div>\r\n");
      out.write("            <img alt=\"incheon\" src=\"img/incheon.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">대구</div>\r\n");
      out.write("            <img alt=\"daegu\" src=\"img/daegu.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">경기</div>\r\n");
      out.write("            <img alt=\"gyeonggi\" src=\"img/Gyeonggi.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">강원</div>\r\n");
      out.write("            <img alt=\"gangwon\" src=\"img/gangwon.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">경남</div>\r\n");
      out.write("            <img alt=\"gyeongnam\" src=\"img/Gyeongsangnam-do.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">경북</div>\r\n");
      out.write("            <img alt=\"gyeongbuk\" src=\"img/Gyeongbuk.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">충남</div>\r\n");
      out.write("            <img alt=\"chungnam\" src=\"img/chungnam.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">충북</div>\r\n");
      out.write("            <img alt=\"chungbuk\" src=\"img/chungbuk.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">전북</div>\r\n");
      out.write("            <img alt=\"jeonbuk\" src=\"img/jeonbuk.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">전남</div>\r\n");
      out.write("            <img alt=\"jeonnam\" src=\"img/jeonnam.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">부산</div>\r\n");
      out.write("            <img alt=\"Busan\" src=\"img/busan.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">#</div>\r\n");
      out.write("            <img alt=\"#\" src=\"img/shap1.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-md-6 col-sm-6 banner\">\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <div class=\"centered\">#</div>\r\n");
      out.write("            <img alt=\"#\" src=\"img/shap2.jpg\">\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"bg-dark\">\r\n");
      out.write("   \r\n");
      out.write("</footer>\r\n");
      out.write("<!--jquery -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<!--popper -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<!--javascript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- datepicker -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#CheckIn\").datepicker({\r\n");
      out.write("\tautoclose : true\r\n");
      out.write("});\r\n");
      out.write("$(\"#CheckOut\").datepicker({\r\n");
      out.write("\tautoclose : true\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t$(\".menu-toggle\").click(function() {\r\n");
      out.write("\t\t$(\"nav\").toggleClass(\"active\")\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
